// Code generated by the Gooo authority projector from .gooo/authority.gooo; DO NOT EDIT.

package projector

const (
	GeneratedAuthorityIdentity = "gooo-output-authority-projector@0.1"
	GeneratedAuthorityDigest   = "sha256:aec01ba0a679faa6cc7dd70551e238bdb2bff47f26ecbd5c3b375ddd44cf2535"
	GeneratedArtifactCount     = 1
)

func GeneratedAuthority() Authority {
	return Authority{
		Identity:   GeneratedAuthorityIdentity,
		Digest:     GeneratedAuthorityDigest,
		Precedence: []Status{StatusRefuted, StatusUnknown, StatusClosed},
		Tools: map[string]Capabilities{
			"projector": {
				InputRoots:              []string{"${CALLER_ROOT}/input"},
				OwnedOutputRoots:        []string{"${CALLER_ROOT}/output"},
				CleanupRoots:            []string{"${CALLER_ROOT}/output"},
				AppendOnlyEvidencePaths: []string{"${CALLER_ROOT}/evidence/replay.jsonl"},
				ForbiddenAncestors:      []string{"${CALLER_ROOT}", "${REPOSITORY_ROOT}"},
				ForbiddenSiblings:       []string{"${CALLER_ROOT}/../sibling"},
			},
			"evidence-writer": {
				InputRoots:              []string{"${CALLER_ROOT}/input"},
				OwnedOutputRoots:        []string{"${CALLER_ROOT}/output/overlap"},
				CleanupRoots:            []string{},
				AppendOnlyEvidencePaths: []string{"${CALLER_ROOT}/evidence/replay.jsonl"},
				ForbiddenAncestors:      []string{"${CALLER_ROOT}", "${REPOSITORY_ROOT}"},
				ForbiddenSiblings:       []string{"${CALLER_ROOT}/../sibling"},
			},
		},
		RepositoryWrites:      0,
		DestructiveOperations: 0,
	}
}

func Project(request Request) Decision {
	return project(request, GeneratedAuthority())
}
